#Name: Haoran Wang
#ID: 505029637
#Email: hwan252@ucla.edu
#_*_MakeFile _*_

#default take the advice from piazza https://piazza.com/class/j83wknjwkhn6vg?cid=407
default:
	echo 'python lab3b.py $$1' > lab3b
	chmod 700 lab3b

clean:
	rm -f lab3b *.tar.gz

dist:
	@tar -czf lab3b-505029637.tar.gz lab3b.py Makefile README